default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rent_a_bike_development

test:
  <<: *default
  database: rent_a_bike_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
